datalake:
  outputs:

    dev:
      type: trino
      method: none
      threads: 4
      host: trino
      port: 8080
      user: admin
      pass: ''
      database: nessie
      schema: raw
  
    prod:
      type: trino
      method: none
      threads: 4
      host: trino
      port: 8080
      user: admin
      pass: ''
      database: nessie
      schema: raw

  target: dev